include:
- project: globalops/BPM/Logistics/DragonFx-DAO/GOLF_Maverick/GoServices/infra-k8s
  ref: v1.0.0
  file: job-templates/cicd-stages.yml
- project: devops/cicd-constructs
  ref: v3.0.0
  file: cicd-constructs.yml
- project: globalops/BPM/Logistics/DragonFx-DAO/GOLF_Maverick/GoServices/infra-k8s
  ref: v1.0.0
  file: job-templates/security-jobs.yml
- project: globalops/BPM/Logistics/DragonFx-DAO/GOLF_Maverick/GoServices/infra-k8s
  ref: v1.0.0
  file: job-templates/versioning.yml

sca-scan:
  extends: .sca-scan-job
  allow_failure: true
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - if: '$CI_COMMIT_BRANCH =~ /DEV/'
  - if: '$CI_COMMIT_BRANCH =~ /REL_PERF/'
  - if: '$CI_COMMIT_BRANCH =~ /REL/'
  - if: '$CI_COMMIT_BRANCH == "main"'

sast-scan:  
  extends: .sast-scan-job
  allow_failure: true
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - if: '$CI_COMMIT_BRANCH == "DEV"'
  - if: '$CI_COMMIT_BRANCH == "REL"'
  - if: '$CI_COMMIT_BRANCH == "REL_PERF"'
  - if: '$CI_COMMIT_BRANCH == "main"'

validate-conventional-commit:
  extends: .validate-conventional-commit

create_durabletask_version:
  extends: .create-durabletask-version
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /DEV/'
    - if: '$CI_COMMIT_BRANCH =~ /REL_PERF/'
    - if: '$CI_COMMIT_BRANCH =~ /REL/'
    - if: '$CI_COMMIT_BRANCH == "main"'